### ISSUE TITLE
New issue with RedBaron

### ISSUE THREAD

**Issue by grandfoosier** [grandfoosier/EMUresearch#2]
I have changed testcode.py to match one of the files I got an error on. If you run test.py now,
you should get the error

Traceback (most recent call last):
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\baron\baron.py", line 20, in _parse
    return parser(tokens)
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\baron\grammator.py", line 828, in parse
    return parser.parse(iter(tokens))
  File "C:\Users\rices\AppData\Local\Programs\Python\Python37-32\lib\site-packages\baron\parser.py", line 167, in parse
    raise ParsingError(debug_output)
baron.parser.ParsingError: Error, got an unexpected token STAR here:

 184     add_to_args = []
 185     if '--debug' not in args_with_config_defaults:
 186         if not tolerate_error_exit_status and '--traceback' not in args_with_config_defaults:
 187             add_to_args.append('--traceback')
 188         if not any('--timeout' in arg for arg in args_with_config_defaults):
 189             add_to_args.append('--timeout=3')
 190
 191     complete_args = [program_name, *<---- here

The token STAR should be one of those: BACKQUOTE, BINARY, BINARY_RAW_STRING, BINARY_STRING, COMPLEX, ELLIPSIS, FLOAT, FLOAT_EXPONANT, FLOAT_EXPONANT_COMPLEX, HEXA, INT, INTERPOLATED_RAW_STRING, INTERPOLATED_STRING, LAMBDA, LEFT_BRACKET, LEFT_PARENTHESIS, LEFT_SQUARE_BRACKET, LONG, MINUS, NAME, NOT, OCTA, PLUS, RAW_STRING, RIGHT_SQUARE_BRACKET, STRING, TILDE, UNICODE_RAW_STRING, UNICODE_STRING

Baron has failed to parse this input. If this is valid python code (and by that I mean that the python binary successfully parse this code without any syntax error) (also consider that python does not yet parse python 3 code integrally) it would be kind if you can extract a snippet of your code that make Baron fails and open a bug here: https://github.com/PyCQA/baron/issues

Sorry for the inconvenience.

It seems like the program will keep running and just skip over that file, so it might be ok for now.

**Comment by grandfoosier** [comment]
("Sorry for the inconvenience." is part of the error BTW)

**Comment by sjiang1** [comment]
It seems redbaron has a lot of buggy issues. Let's put these `testcode` files in a folder. Meanwhile, I'd like you to write a program and run redbaron on at least 5 python projects, and see how many errors we can get and how many files can be actually parsed by RedBaron. Thanks!

**Comment by grandfoosier** [comment]
I think the multi-threading is helping it go faster, but I'm not too familiar with it, and I'm not sure if it's the reason the program hung in the middle of running django.
Here are the stats so far:

donnemartin/system-design-primer: 14 source files successfully read
vinta/awesome-python: 1 successful
public-apis/public-apis: 2 successful
tensorflow/models: 1576 successful, 17 unsuccessful
ytdl-org/youtube-dl: skipped for now
nvbn/thefuck: 366 successful
pallets/flask: 70 successful
keras-team/keras: 196 successful
django/django: 1952 successful, 103 unsuccessful. The program also hung once and I had to ctrl-c

This produced 39,053 output files from 4177 source with 120 failed source files.

**Comment by sjiang1** [comment]
Great job! ~3% failure rate is acceptable. To check if multi-threading is a problem, you can try running django again to see if we have the same failed source files. A problem in multi-threading may cause different outputs every time we run the problem.

For now, I will just put this ~3% in our report, and it should be fine. Let me know if you've finished Task 2. #1
