### ISSUE TITLE
Task 3 - Download files of specific commits

### ISSUE THREAD

**Issue by sjiang1** [grandfoosier/EMUresearch#3]
I just updated the pythonProjectIndex.txt so that for each Python project, we have its latest commit id (i.e., SHA). I would like you to extract methods from the files of these specific commits.

The reason we want to do that is in this way, we can make sure every time we run the script, we get the same data set. Others can reproduce our work if necessary.

Thanks!

**Comment by grandfoosier** [comment]
Some of the projects don't have hashes. Also, for something like

0	07b50f616e407c8b7b2c183298acbb58e2ddf09b	1(1),

what does the 0 and the 1(1) mean?

**Comment by sjiang1** [comment]
That's the information about GitHub search results. I use **tabs** to separate the columns.
for `1(1)` it means, the project appears on the first search result page (github in total returns 10 pages of search results.) Some projects appear on multiple pages. That's why you can see some lines like this one:

```
166     lucperkins      colossus        https://github.com/lucperkins/colossus.git      1       10(1), 2(1),
```
This means that `lucperkins/colossus` is on both page 10 and page 2. The first `1` indicates the project has a duplicate in the search results.

I will check why some projects don't have SHA.

**Comment by sjiang1** [comment]
at least for lucperkins/colossus, it has no master branch, but a main branch. would you count how many projects don't have an SHA? I'll see what I am going to do about it.

**Comment by grandfoosier** [comment]
5	ansible	ansible	https://github.com/ansible/ansible.git	0	1(1), 
29	bitcoinbook	bitcoinbook	https://github.com/bitcoinbook/bitcoinbook.git	0	1(1), 
65	ansible	awx	https://github.com/ansible/awx.git	0	1(1), 
85	Gallopsled	pwntools	https://github.com/Gallopsled/pwntools.git	0	1(1), 
166	lucperkins	colossus	https://github.com/lucperkins/colossus.git	1	10(1), 2(1), 
430	RocketMap	RocketMap	https://github.com/RocketMap/RocketMap.git	0	5(1), 
805	xybu	onedrive-d-old	https://github.com/xybu/onedrive-d-old.git	0	10(1), 
837	nilboy	tensorflow-yolo	https://github.com/nilboy/tensorflow-yolo.git	0	10(1),

**Comment by sjiang1** [comment]
Thanks! I will fix them later. For now, we will just leave them there.

**Comment by grandfoosier** [comment]
I pushed the new code. As of right now, a project without a commit hash will be skipped. I could change it to use master instead though

**Comment by sjiang1** [comment]
Thanks! I will check it next week.

**Comment by sjiang1** [comment]
I am running the code now. Why in the output path, there are two commit ids?

For example, there are two '7e05df71b7d8c0e1ea9beafff48275ef3c9e27d2' in the path:
```
out/ytdl-org/youtube-dl/7e05df71b7d8c0e1ea9beafff48275ef3c9e27d2/youtube_dl/extractor/bpb.porg/youtube-dl/7e05df71b7d8c0e1ea9beafff48275ef3c9e27d2/youtube_dl/extractor/
```

**Comment by grandfoosier** [comment]
The issue was I was still trying to remove "/master/" from the directory name, but since it wasn't in there, the find was returning -1, and then the directory ended up being something like addB[:-1]+addB[s:], so everything from s to the last character got duplicated. I removed that stuff and it's working now.

**Comment by sjiang1** [comment]
Great, I will try that. I fixed that problem of some projects missing commits. So I will update the project index file today or tomorrow.
